# Generated by Django 5.2 on 2025-09-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_layer_monitor', '0004_spatialmonitorhistory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('geoserver_group', models.IntegerField(choices=[(0, 'KMI'), (1, 'KB')], default=0)),
                ('endpoint_url', models.CharField(max_length=500)),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
