# Generated by Django 5.2 on 2025-09-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_layer_monitor', '0005_geoserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialmonitor',
            name='geoserver_group',
            field=models.IntegerField(choices=[(0, 'KMI'), (1, 'KB')], default=0),
        ),
    ]
