# Generated by Django 5.2.9 on 2026-01-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_layer_monitor', '0006_spatialmonitor_geoserver_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spatialmonitor',
            options={'verbose_name': 'spatial layer monitor', 'verbose_name_plural': 'spatial layer monitors'},
        ),
        migrations.AlterModelOptions(
            name='spatialmonitorhistory',
            options={'verbose_name': 'spatial layer monitor history', 'verbose_name_plural': 'spatial layer monitor histories'},
        ),
        migrations.AddField(
            model_name='spatialmonitorhistory',
            name='last_purge_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spatialmonitorhistory',
            name='purge_processing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spatialmonitorhistory',
            name='purge_retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spatialmonitorhistory',
            name='purge_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
