# Generated by Django 5.2.4 on 2025-12-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_layer_monitor', '0006_spatialmonitor_geoserver_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialmonitorhistory',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spatialmonitorhistory',
            name='retry_failure_count',
            field=models.IntegerField(default=0),
        ),
    ]
