# Generated by Django 5.2.9 on 2026-01-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_layer_monitor', '0007_alter_spatialmonitor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialmonitorhistory',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Processing'), (2, 'Success'), (3, 'Failed')], db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='spatialmonitorhistory',
            name='status_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
