# Generated by Django 5.2.4 on 2025-12-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_layer_monitor', '0007_spatialmonitorhistory_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialmonitorhistory',
            name='hash',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
