# Generated by Django 5.2.9 on 2026-01-09 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_layer_monitor', '0008_spatialmonitorhistory_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spatialmonitorhistory',
            name='purge_status',
        ),
    ]
