# Generated by Django 5.2.10 on 2026-01-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_layer_monitor', '0009_remove_spatialmonitorhistory_purge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialmonitor',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
